name: データ加工・フロントエンド配置

on:
  workflow_run:
    workflows: ["議事録データ収集"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      process_all:
        description: '全データを再加工するか'
        required: false
        default: false
        type: boolean

jobs:
  process-data:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Setup uv environment
      working-directory: scripts/uv-data-collection
      run: |
        uv sync
        
    - name: Process collected data
      working-directory: scripts/uv-data-collection
      env:
        PROCESS_ALL: ${{ github.event.inputs.process_all || 'false' }}
      run: |
        uv run python data_processing_pipeline.py
        
    - name: Deploy to frontend
      run: |
        cp data/processed/speeches/* frontend/public/data/speeches/
        cp data/processed/manifestos/* frontend/public/data/manifestos/ || true
        cp data/processed/analysis/* frontend/public/data/analysis/ || true
        
    - name: Test frontend build
      run: |
        cd frontend
        npm ci
        npm run build
        
    - name: Commit processed data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add frontend/public/data/
        git diff --staged --quiet || git commit -m "データ加工完了: $(date '+%Y-%m-%d %H:%M:%S')"
        git push